/// @desc Demo configuration

// Fuction keyword macros (duplicated from 'aStar' script to be modular
#macro SHIFT 16						// Bitwise shortcut
#macro MASK 65535					// Bitwise shortcut

// All-purpose macros
#macro COLS 50						// Number of node columns
#macro ROWS 25						// Number of node rows
#macro SIZE 32						// The size of a single tile
#macro SIDES 4						// Number of sides, used by graph loop in 'aStar' script

// Keybind macros
#macro PATH mb_left					// Keybind for initiating a path
#macro MOVE mb_right				// Keybind for teleporting player

// A* settings
global.BLOCKED=ds_list_create();	// List containing pointers of all blocked nodes
path=ds_list_create();				// This list is generated by aStar algorithm script

// Demo GUI debug variables
SPRITE=ds_grid_create(50,25);		// List sprites used for the demo GUI
STEPS=ds_grid_create(50,25);		// List of steps taken used for the demo GUI
scans=0;							// Total number of nodes scanned
length=0;							// Length of path
time=0;								// Time taken to calculate path

// Player object configuration
pathing=false;						// Boolean used to gate input and path following logic
spd=20;								// Speed that object moves along the path